  # Name of workflow
  name: My Test Workflow


  #Define the trigger event(s)
  on:  [push]

  # List of jobs. They run in paralel. The steps are in the list and they;re run in sequence
  jobs:


      say-hello:
          runs-on: ubuntu-latest
          steps:
              - run: echo "Hello GitHub Actions!"
              
