  # Name of workflow
    name: My Test Workflow


  #Define the trigger event(s)
    on:  [push]

  # List of jobs. They run in paralel. The steps are in the list and they;re run in sequence
    jobs:

        # Job to print something out
        say-hello:
            runs-on: ubuntu-latest
            steps:
                - run: echo "Hello GitHub Actions!" #this step could also be named with -name. see code below
        
        # job to build and test our C code
        build-and-test:
            needs:  [say-hello]
            runs-on: ubuntu-latest
            steps:

                # Use github.com/actions/checout to check out this repo
                - name: Check out this repo
                  uses: actions/checkout@v3
                
                # Install necessery packages
                - name: Install depencdencies
                  run: sudo apt install -y build essential python3
                
                # See where we are in the VM
                - run: pwd

                #Run our test
                - name: Run test
                  run: python3 test.py



    
              
